export const projectArchitectures = [
  {
    name: "Incident investigation",
    note: "Alert → durable outbox → evidence investigation → optional RAG/Gemini RCA → operator review",
    viewBox: "0 0 1000 470",
    stages: [
      { title: "Detect", nodes: ["Prometheus", "Alertmanager"], detail: "Prometheus evaluates service telemetry and Alertmanager sends firing or resolved webhooks. The incident service deduplicates active incidents by fingerprint before creating new work." },
      { title: "Preserve", nodes: ["Incident API", "PostgreSQL", "Transactional outbox"], detail: "Incident state and the investigation request are persisted in one transaction. A scheduled outbox publisher sends unpublished events to Kafka and retries them safely after broker failures." },
      { title: "Investigate", nodes: ["Kafka worker", "Prometheus", "Loki", "Tempo"], detail: "The investigation worker loads the incident, collects a five-minute evidence window from metrics, error logs, and traces, redacts sensitive log values, and completes a deterministic evidence-backed analysis even when one telemetry source is unavailable." },
      { title: "Enrich with AI", nodes: ["AI topic", "Gemini embeddings", "pgvector RAG", "Gemini RCA"], detail: "After deterministic investigation completes, a second outbox event can trigger the AI service. Live evidence is embedded, similar runbooks and past incidents are retrieved from pgvector, and Gemini returns a structured root-cause hypothesis with confidence, supporting/counter evidence, recommendations, and missing information." },
      { title: "Review", nodes: ["PostgreSQL", "Incident Desk", "Grafana", "AI investigation API"], detail: "The normal incident report and AI hypothesis are persisted separately. Operators can review durable incident history, telemetry evidence, dashboards, and the optional AI investigation without making the core incident workflow depend on the model." },
    ],
    nodes: [
      { id: "prom", x: 78, y: 70, label: "Prometheus", stage: 0 },
      { id: "alert", x: 220, y: 70, label: "Alertmanager", stage: 0 },
      { id: "api", x: 375, y: 70, label: "Incident API", stage: 1 },
      { id: "db", x: 530, y: 38, label: "PostgreSQL", stage: 1 },
      { id: "outbox", x: 530, y: 112, label: "Outbox", stage: 1 },
      { id: "kafka", x: 690, y: 112, label: "Kafka", stage: 2 },
      { id: "worker", x: 690, y: 225, label: "Evidence worker", stage: 2 },
      { id: "telemetry", x: 525, y: 260, label: "Telemetry", sub: "Prom · Loki · Tempo", stage: 2 },
      { id: "report", x: 350, y: 260, label: "Incident report", stage: 2 },
      { id: "aitopic", x: 350, y: 355, label: "AI topic", sub: "outbox → Kafka", stage: 3 },
      { id: "aiworker", x: 515, y: 355, label: "AI worker", stage: 3 },
      { id: "embed", x: 680, y: 330, label: "Gemini embed", stage: 3 },
      { id: "vector", x: 845, y: 330, label: "pgvector", sub: "runbooks · history", stage: 3 },
      { id: "gemini", x: 845, y: 405, label: "Gemini RCA", sub: "structured hypothesis", stage: 3 },
      { id: "review", x: 155, y: 355, label: "Desk / Grafana", stage: 4 },
      { id: "aiapi", x: 155, y: 430, label: "AI API", sub: "persisted hypothesis", stage: 4 },
    ],
    edges: [
      { id: "i1", d: "M78 70 H220", stage: 0 }, { id: "i2", d: "M220 70 H375", stage: 0 },
      { id: "i3", d: "M375 70 H455 V38 H530", stage: 1 }, { id: "i4", d: "M375 70 H455 V112 H530", stage: 1 },
      { id: "i5", d: "M530 112 H690", stage: 2 }, { id: "i6", d: "M690 112 V225", stage: 2 },
      { id: "i7", d: "M690 225 H610 V260 H525", stage: 2 }, { id: "i8", d: "M525 260 H350", stage: 2 },
      { id: "i9", d: "M350 260 V355", stage: 3 }, { id: "i10", d: "M350 355 H515", stage: 3 },
      { id: "i11", d: "M515 355 H600 V330 H680", stage: 3 }, { id: "i12", d: "M680 330 H845", stage: 3 },
      { id: "i13", d: "M845 330 V405", stage: 3 }, { id: "i14", d: "M350 260 H250 V355 H155", stage: 4 },
      { id: "i15", d: "M845 405 H750 V430 H155", stage: 4, muted: true },
    ],
  },
  {
    name: "News intelligence",
    note: "Redis cache → concurrent providers → normalized feed → citation-validated Gemini workspace",
    viewBox: "0 0 1000 420",
    stages: [
      { title: "Request", nodes: ["React client", "Search API", "Redis search cache"], detail: "The client uses one backend search contract. The backend normalizes the keyword and page request and first checks the Redis-backed search cache." },
      { title: "Fan out", nodes: ["Virtual-thread executor", "Guardian", "NYT", "Timeout budget"], detail: "On a cache miss, enabled provider adapters run concurrently with CompletableFuture on the configured executor. Each provider has a timeout, and useful partial results survive when another publisher fails." },
      { title: "Normalize", nodes: ["Adapter layer", "Deduplicate", "Sort & paginate", "Redis"], detail: "Guardian and NYT responses are mapped into one article model, merged and deduplicated, sorted and paginated, then cached so repeated searches avoid unnecessary provider calls." },
      { title: "Ground AI", nodes: ["AI workspace", "Gemini", "Citation validation", "AI Redis cache"], detail: "Summary, why-it-matters, daily brief, ask, and compare endpoints send only supplied articles to Gemini. Structured source IDs are validated server-side, requests are rate-limited, and AI responses use their own Redis cache while search remains usable without AI." },
    ],
    nodes: [
      { id: "client", x: 92, y: 205, label: "React", stage: 0 },
      { id: "api", x: 245, y: 205, label: "Search API", stage: 0 },
      { id: "cache", x: 400, y: 80, label: "Redis", sub: "search cache", stage: 0 },
      { id: "guardian", x: 435, y: 180, label: "Guardian", stage: 1 },
      { id: "nyt", x: 435, y: 305, label: "NYT", stage: 1 },
      { id: "normalize", x: 615, y: 205, label: "Normalize", sub: "dedupe · sort", stage: 2 },
      { id: "store", x: 785, y: 95, label: "Redis", sub: "search result", stage: 2 },
      { id: "gemini", x: 785, y: 300, label: "Gemini", sub: "structured AI", stage: 3 },
      { id: "aicache", x: 610, y: 345, label: "AI cache", sub: "Redis TTL", stage: 3 },
      { id: "result", x: 920, y: 205, label: "Cited response", stage: 3 },
    ],
    edges: [
      { id: "n1", d: "M92 205 H245", stage: 0 }, { id: "n2", d: "M245 205 H320 V80 H400", stage: 0 },
      { id: "n3", d: "M245 205 H335 V180 H435", stage: 1 }, { id: "n4", d: "M245 205 H335 V305 H435", stage: 1 },
      { id: "n5", d: "M435 180 H525 V205 H615", stage: 2 }, { id: "n6", d: "M435 305 H525 V205 H615", stage: 2 },
      { id: "n7", d: "M615 205 H700 V95 H785", stage: 2 }, { id: "n8", d: "M615 205 H700 V300 H785", stage: 3 },
      { id: "n9", d: "M615 205 V345", stage: 3 }, { id: "n10", d: "M785 300 H855 V205 H920", stage: 3 },
    ],
  },
  {
    name: "Room-based messaging",
    note: "Idempotent REST write → sequenced MongoDB state → STOMP live delivery → cursor recovery",
    viewBox: "0 0 1000 420",
    stages: [
      { title: "Write", nodes: ["React client", "clientMessageId", "REST message API"], detail: "The UI creates a client message ID and optimistically tracks pending state. Sends use the retryable REST path so the same request ID can be retried after transient failures." },
      { title: "Persist", nodes: ["Striped room lock", "MongoDB", "Atomic room sequence"], detail: "The backend serializes writers per room with striped locks, rejects reuse of the same request ID with different content, atomically increments the room sequence, and persists the message before live delivery." },
      { title: "Broadcast", nodes: ["STOMP/SockJS", "Room topic", "Presence topic"], detail: "After persistence, Spring publishes the saved message to the room topic. Separate WebSocket connect/disconnect events maintain in-memory room presence and broadcast online/offline snapshots." },
      { title: "Recover", nodes: ["Cursor history", "Periodic sync", "Reconnect", "Merge by ID & sequence"], detail: "The client loads recent history, repeatedly fetches messages after its confirmed sequence cursor, reconnects STOMP automatically, and merges history with live events so a missed WebSocket notification is recovered from MongoDB." },
    ],
    nodes: [
      { id: "client", x: 90, y: 205, label: "React client", stage: 0 },
      { id: "rest", x: 245, y: 205, label: "REST write", sub: "clientMessageId", stage: 0 },
      { id: "lock", x: 400, y: 205, label: "Room writer", sub: "striped lock", stage: 1 },
      { id: "mongo", x: 560, y: 95, label: "MongoDB", sub: "message state", stage: 1 },
      { id: "seq", x: 560, y: 285, label: "Room sequence", sub: "atomic increment", stage: 1 },
      { id: "stomp", x: 725, y: 285, label: "STOMP/SockJS", stage: 2 },
      { id: "presence", x: 725, y: 95, label: "Presence", sub: "connect · disconnect", stage: 2 },
      { id: "room", x: 885, y: 285, label: "Room topic", stage: 2 },
      { id: "history", x: 885, y: 95, label: "History API", sub: "before / after", stage: 3 },
      { id: "sync", x: 885, y: 390, label: "Reconnect sync", sub: "merge ID + sequence", stage: 3 },
    ],
    edges: [
      { id: "c1", d: "M90 205 H245", stage: 0 }, { id: "c2", d: "M245 205 H400", stage: 1 },
      { id: "c3", d: "M400 205 H480 V95 H560", stage: 1 }, { id: "c4", d: "M400 205 H480 V285 H560", stage: 1 },
      { id: "c5", d: "M560 285 H725", stage: 2 }, { id: "c6", d: "M725 285 H885", stage: 2 },
      { id: "c7", d: "M725 95 H885", stage: 2 }, { id: "c8", d: "M560 95 H885", stage: 3 },
      { id: "c9", d: "M885 95 V390", stage: 3 }, { id: "c10", d: "M885 390 H90 V205", stage: 3, muted: true },
    ],
  },
];
